apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-project-cloud-devops
  labels:
    app: capstone-project-cloud-devops
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-project-cloud-devops
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-project-cloud-devops
    spec:
      containers:
        - image: sabbir33/capstone-project-cloud-devops
          imagePullPolicy: Always
          name: capstone-project-cloud-devops
          ports:
            - containerPort: 80
